
spring :
  datasource :
    url : jdbc:mysql://localhost:3306/auth?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useAffectedRows=true&useSSL=false&serverTimezone=GMT%2B8
    username : root
    password : 123456
    driverClassName : com.mysql.cj.jdbc.Driver
    platform: mysql
#    schema: classpath:/schema.sql
    initialization-mode: embedded
mybatis :
  config-location : classpath:/mybatis-config.xml
  mapper-locations: classpath*:mapper/*.xml
# JWT
jwt:
  header: Authorization
  secret: mySecret
  #token有效期一天
  expiration: 86400
  tokenHead: "Bearer "
server:
  port: 8081